# 此文件包含 fastlane.tools 配置您可以在以下位置找到文档 https://docs.fastlane.tools

platform :android do
  
  # track:
  #   internal 内部测试
  #   alpha Alpha测试
  #   beta 开放测试
  #   production 生产
  # aab:
  #   要上传的 AAB 文件的路径

  desc "将新的 Android 版本上传到 Google Play 商店 (内部测试)"
  lane :internal do
    upload_to_play_store(aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}", track: "internal") 
  end
  
  desc "将新的 Android 版本上传到 Google Play 商店 (Alpha测试)"
  lane :alpha do
    upload_to_play_store(aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}", track: "alpha") 
  end
  
  desc "将新的 Android 版本上传到 Google Play 商店 (开放测试)"
  lane :beta do
    upload_to_play_store(aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}", track: "beta") 
  end
    
  desc "将新的 Android 版本上传到 Google Play 商店 (生产)"
  lane :production do
    upload_to_play_store(aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}", track: "production") 
  end

end


platform :ios do

  desc "向 App Store 交付新的 Release 版本"
  lane :release do
    build
    deliver
  end

  desc "为 Apple TestFlight 提供新的 Beta 版本"
  lane :beta do
    build
    upload_to_testflight(skip_waiting_for_build_processing: true) # 如果设置为 true，则该选项将不起作用，并且不会向测试人员分发任何内部版本。
  end

  desc "创建.ipa"
  lane :build do
    setup_ci
    app_store_connect_api_key(
      key_id: ENV['APPSTORE_KEY_ID'], # 密钥标识
      issuer_id: ENV['APPSTORE_ISSUER_ID'], # 颁发者 ID
      key_content: ENV['APPSTORE_P8'] # 密钥 p8 文件的内容
    )
    match(
      type: 'appstore',
      storage_mode: 'git',
      git_url: ENV['MATCH_URL'],
      git_basic_authorization: Base64.strict_encode64("#{ENV['APPLE_CONNECT_EMAIL']}:#{ENV['MATCH_PERSONAL_ACCESS_TOKEN']}"),
      app_identifier: ENV['IOS_APP_ID']
    )
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj"
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV["sigh_#{ENV['IOS_APP_ID']}_appstore_team-id"],
      code_sign_identity: 'iPhone Distribution',
      targets: 'Unity-iPhone',
      path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      profile_name: ENV["sigh_#{ENV['IOS_APP_ID']}_appstore_profile-name"],
      profile_uuid: ENV["sigh_#{ENV['IOS_APP_ID']}_appstore"]
    )
    cocoapods(
      clean_install: true,
      podfile: "#{ENV['IOS_BUILD_PATH']}/iOS/"
    )
    set_info_plist_value(path: "#{ENV['IOS_BUILD_PATH']}/iOS/Info.plist",
      key: "FirebaseDynamicLinksCustomDomains",
      value: "https://cgs.link"
    )
    build_app(
      workspace: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcworkspace",
      scheme: 'Unity-iPhone',
      xcargs: '-allowProvisioningUpdates'
    )
  end

end


platform :mac do

  desc "破解以便 Apple 不会因为版本控制错误而拒绝 mac 构建" 
  lane :fixversion do
    update_plist(
      plist_path: "#{ENV['MAC_BUILD_PATH']}/StandaloneOSX.app/Contents/Info.plist",
      block: proc do |plist|
        plist[:CFBundleVersion] = '9' + plist['CFBundleVersion']
      end
    )
  end

  desc "将新的 Mac 版本上传到 Mac App Store"
  lane :macupload do
    app_store_connect_api_key(
      key_id: ENV['APPSTORE_KEY_ID'],
      issuer_id: ENV['APPSTORE_ISSUER_ID'],
      key_content: ENV['APPSTORE_P8']
    )
    deliver
  end

end
